### ISSUE TITLE
bug: When middleware enabled, user is still authenticated after JWT has been revoked

### ISSUE THREAD

**Issue by jonathanrich1986** [nicumicle/simple-jwt-login#110] opened 2024-05-08 13:19 UTC
# Bug Report

## Plugin Version
3.5.5

## PHP Version
8.1.23

## WordPress Version
6.5.3

## Bug description
I have the setting "All WordPress endpoints checks for JWT authentication" enabled. However when I revoke a JWT, the user is still getting set as the current user for a request. I have checked that the token is definitely revoked using the validate endpoint. I would expect the response to return 401 if the token has been revoked.

**Comment by nicumicle** [comment] 2024-05-09 08:14
Hi @jonathanrich1986 ,

Thanks for reporting this bug.

The issue is fixed now. 
You can download the plugin with the fix from [https://simplejwtlogin.com](https://simplejwtlogin.com).

I will do a release soon to include this change. :rocket: 

Best Regards,
Nicu.

**Comment by jonathanrich1986** [comment] 2024-05-15 15:53
@nicumicle Thanks this works now

**Closed** 2024-05-15 18:01 UTC
Labels: bug
